apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
        - name: wisecow
          image: ghcr.io/aishwini08/wisecow:380bf4ead871e47fdcc32fd632e76fdccd06ab31
          imagePullPolicy: Never
          ports:
            - containerPort: 4499